#!/bin/sh
exec tail -n +3 $0
# This file provides an easy way to add custom menu entries.  Simply type the
# menu entries you want to add after this comment.  Be careful not to change
# the 'exec tail' line above.
if [ "${grub_platform}" == "efi" ]; then
	menuentry "Windows 10" {
		insmod part_gpt
		insmod fat
		insmod search_fs_uuid
		insmod chain
		search --fs-uuid --set=root $fs_uuid
		# use:
		# grub-probe --target=fs_uuid /EFI/Microsoft/Boot/bootmgfw.efi
		chainloader /EFI/Microsoft/Boot/bootmgfw.efi
	}
fi
